### DISCUSSION TITLE
How to filter the output of a get request that return an array of elements ?

### DISCUSSION THREAD

**Discussion by BragdonD** [OAI/Arazzo-Specification#327] [Q&A]
Hello, 

I was reading the examples provided [in this folder](https://github.com/OAI/Arazzo-Specification/blob/main/examples/1.0.0/), to understand how I could described my API with the Arazzo specification. 

I stumbled on this comment:

````yaml
steps:
  - stepId: find-pet
    description: Find a pet based on the provided tags.
    operationId: findPetsByTags
    parameters:
      - name: pet_tags
        in: query
        value: $inputs.my_pet_tags
    successCriteria:
      - condition: $statusCode == 200
    outputs:
      my_pet_id: $response.body#/0/id
      # there is some implied selection here - findPetsByTags responds with a list of pets,
      # but the client only wants to choose one, and that's what will be provided to the next step.
      # not totally sure how to indicate that.
````

I read across the documentation and I could not find an answer to this question. 

Is there any ways to do it ? If no, is it something that will be defined in the future ?
