### ISSUE TITLE
Handle `servers` variable params

### ISSUE THREAD

**Issue by DmitryAnansky** [OAI/Arazzo-Specification#218]
Hi Everyone,

I encountered a scenario that isn't explicitly covered in the documentation, and I'm hoping you can clarify it for me.
It is possible to define server variables in OpenAPI like this:

```
servers:
  - url: 'https://api-url.example.com/organizations/{organizationId}'
    description: api server
    variables:
      organizationId:
        default: unknown
        description: >-
          Unique organization identifier.
``` 

My confusion arises from how to pass this `organizationId` to the step parameters.
My assumption was to pass it as a parameter like this:

```
    steps:
      - stepId: getData
        operationId: GetData
        parameters:
          - in: path
            name: organizationId
            value: someOrg
```

However, it seems that this `organizationId` parameter doesn't actually belong to the parameters in the `path`, but rather to the server variables.
Please let me know if you have some configuration in mind, maybe you already discussed it before.

Looking forward to your reply,
Thank you.
